package com.smarthealth.logic;

import com.itextpdf.kernel.pdf.PdfDocument;
import com.itextpdf.kernel.pdf.PdfWriter;
import com.itextpdf.layout.Document;
import com.itextpdf.layout.element.Paragraph;
import com.smarthealth.model.Patient;

import java.io.FileNotFoundException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 * Handles PDF report generation for patients.
 */
public class HealthReportGenerator {

    /**
     * Generates a PDF report for a patient.
     * @param patient The patient object
     * @param diagnosis The last diagnosis result
     * @return Path to the generated PDF
     */
    public String generateReport(Patient patient, String diagnosis) {
        String fileName = "Report_" + patient.getId() + "_" + System.currentTimeMillis() + ".pdf";
        try {
            PdfWriter writer = new PdfWriter(fileName);
            PdfDocument pdf = new PdfDocument(writer);
            Document document = new Document(pdf);

            document.add(new Paragraph("Smart Healthcare System - Patient Report").setBold().setFontSize(18));
            document.add(new Paragraph("Generated on: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"))));
            document.add(new Paragraph("--------------------------------------------------"));

            document.add(new Paragraph("Patient Details:"));
            document.add(new Paragraph("ID: " + patient.getId()));
            document.add(new Paragraph("Name: " + patient.getName()));
            document.add(new Paragraph("Age: " + patient.getAge()));
            document.add(new Paragraph("Gender: " + patient.getGender()));

            document.add(new Paragraph("--------------------------------------------------"));
            document.add(new Paragraph("Latest Diagnosis / Symptom Check Result:"));
            document.add(new Paragraph(diagnosis));

            document.add(new Paragraph("--------------------------------------------------"));
            document.add(new Paragraph("Disclaimer: This report is generated by an automated system and should not replace professional medical advice."));

            document.close();
            return "Report generated successfully: " + fileName;
        } catch (FileNotFoundException e) {
            return "Error generating report: " + e.getMessage();
        }
    }
}
